#!/bin/sh

# The following requires GNU sed.
SED_SCRIPT='
1 {
  i\# Generated by .config/script/notify_new_mail.sh
  i\# (probably launched after all offlineimap run)
}

s/mailboxes//
s| "+\([^[:space:]]\+\)"|$(HOME)/mail/\1\n|g
'

cat ~/.config/mutt/accounts/mailboxes | sed "$SED_SCRIPT" > ~/.mailcheckrc

STATUS=`mailcheck -c`
if test "$STATUS" != ""; then
    notify.py -1 "New Mail" "$STATUS";
fi
