#!/bin/bash

CONFIG_HOME=`[ -n "$XDG_CONFIG_HOME" ] && echo $XDG_CONFIG_HOME || echo $HOME/.config`
MB_FILE=$CONFIG_HOME/mutt/accounts/mailboxes
RC_DIR=$CONFIG_HOME/mailcheck
RC_BASE=$RC_DIR/mailcheckrc

# The following requires GNU sed.
SED_SCRIPT='
1 {
  i\# Generated by .config/script/notify_new_mail.sh
}

s/mailboxes//
s| "+\([^[:space:]]\+\)"|$(HOME)/mail/\1\n|g
'

send_notification () {
    local rc_file="$RC_BASE"
    local msg=""

    [ $# -eq 1 ] && { rc_file="$rc_file"_$1; msg=" ($1)"; }

    local status=`mailcheck -c -f "$rc_file"`

    [ -n "$status" ] && $CONFIG_HOME/scripts/notify.py -1 "New Mail $msg" "$status";
}

[ $# -gt 1 ] && { trap_error "wrong arguments."; exit -1; }

[ -d "$RC_DIR" ] || { mkdir -p "$RC_DIR"; }

# Refresh the base configuration file.
cat "$MB_FILE" | sed "$SED_SCRIPT" > "$RC_BASE"

# Refresh the required configuration file if necessary.
[ $# -eq 1 ] && { cat "$RC_BASE" | grep $1 > "$RC_BASE"_$1; }

# Send notification
send_notification $1
